### ISSUE TITLE
Broken code

### ISSUE THREAD

**Issue by Creative-Punch** [udibr/VAE#1]
Hi there,

It looks like the code broke with the current version of Blocks and Fuel, generating multiple import errors due to renames and one dimension error on the "features" symbolic matrix.

**Comment by Creative-Punch** [comment]
Ok so I determined that Dump should change to Checkpoint and LoadFromDump should become Load. "Sigmoid" also changed to "Logistic" and you are now required to use fuel.tranformers.Flatten on your DataStream.

However after all these fixes the results are all messed up. The NLL goes to values such as -1.000.000 though this might have been an issue before those changes

**Comment by udibr** [comment]
I am busy for the next two weeks. So if you have a fix please send me a pull request. I did similar fix to using fuel in my sketch project which is up to date.

**Comment by udibr** [comment]
fixed https://github.com/udibr/VAE/commit/d1bd144ace5450f40ecec0a44c0cb920258bbaf4
